### ISSUE TITLE
memory leakage problem?

### ISSUE THREAD

**Issue by Minotaur-CN** [moliusimon/csdm#1]
Dear moliusimon,
I am appreciate your interesting job at first,But I found the memory wereincreast when training the CSDM model. may be a memory leakage problem? Have you had this situation before?
Thanks for you reply!
The memory ware 300M at first, and reachd 2.4G when trainging abount 50mins.
The same situation when I run the code at ubuntu.1404

If not the memory leakage problem, How many memory shoud I need for 300W-dataSet training!

![image](https://cloud.githubusercontent.com/assets/9798125/18814036/fec5b458-8340-11e6-9e8d-ca4df764b6b9.png)

**Comment by moliusimon** [comment]
Dear Minotaur-CN, unfortunately the memory usage is quite intensive. Initially the memory usage is low because of the 300-w dataset not containing too many images, but an agressive data augmentation (25x augmentation) is performed, which starts to consume lots of memory when extracting the SIFT features from all of them during training, and then performing PCA on these features. As a rough rule of thumb, we used up around 32gb of RAM for training. During test the model is much faster, and doesn't consume much memory.

If your goal is to just train the model for practical use (not necessarily on 300-w), it is much faster to train it on BU4DFE-S. The reason is this synthetic dataset has a much higher variability, which means that, although there are more images, no augmentation is required. It is about 4 times faster to train, and requires around 20gb of RAM to train.

**Comment by Minotaur-CN** [comment]
Dear moliusimon,
Thanks for your reply. I will try on a better machine later.
